const LIGHT_TYPE_INVALID: u32 = 0u;
const LIGHT_TYPE_AREA: u32 = 1u;
const LIGHT_TYPE_DIRECTIONAL: u32 = 2u;
const LIGHT_TYPE_POINT: u32 = 3u;
const LIGHT_TYPE_SPOT: u32 = 4u;

const LIGHT_AREA_RRCT: u32 = 0u;
const LIGHT_AREA_DISC: u32 = 1u;
